{
 "title": "Manage - Personal Dashboard",
 "tags": [
  "ConnectWise",
  "Personal Dashboard"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cw_api_url",
    "label": "i.e. https://api-au.myconnectwise.net/v4_6_release",
    "query": "${VAR_CW_API_URL}"
   },
   {
    "name": "cw_company_id",
    "label": "Your MSP's company ID as it is in ConnectWise Manage",
    "query": "${VAR_CW_COMPANY_ID}"
   },
   {
    "name": "cw_db_name",
    "label": "Database Name i.e. cwwebapp_yourmsp",
    "query": "${VAR_CW_DB_NAME}"
   },
   { "name": "cw_locale", "query": "${VAR_CW_LOCALE}" },
   {
    "name": "cw_user",
    "label": "User:",
    "query": "SELECT [Member_ID]\nFROM [${cw_db_name}].[dbo].[v_api_collection_system_member]\nWHERE [Inactive_Flag] = 0\n    AND [Member_Class] = 'F'\n    AND [Member_Name] NOT LIKE '%#%'\n    AND [Date_Hire] IS NOT NULL"
   },
   {
    "name": "cw_board",
    "label": "Board:",
    "query": "SELECT [Board_Name]\nFROM [${cw_db_name}].[dbo].[v_api_collection_service_board]\nWHERE [Inactive_Flag] = 0\n    AND [Activity_Type_RecID] = 51"
   },
   { "name": "grafana_url", "query": "${VAR_GRAFANA_URL}" },
   {
    "name": "random_delay",
    "label": "Random delay, between zero and $random_delay seconds",
    "query": "${VAR_RANDOM_DELAY}"
   }
  ]
 },
 "panels": [
  {
   "title": "Assigned Support Tickets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\r\nFROM\r\n    [${cw_db_name}].[dbo].[v_api_collection_service_ticket]\r\nWHERE\r\n    [Board_Name] IN(${cw_board:sqlstring}) AND\r\n    [ResourceList] IN(${cw_user:sqlstring}) AND\r\n    [Closed_Flag] = 0 AND\r\n    [parentTicketId] IS NULL"
    }
   ]
  },
  {
   "title": "Open Tickets",
   "type": "table",
   "gridPos": { "h": 16, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    [SR_Service_RecID],\r\n    [Summary],\r\n    [Board_Name],\r\n    [Status_Name],\r\n    [Company_ID],\r\n    [Closed_Flag],\r\n    [SR_Type_Name],\r\n    [SR_SubType_Name],\r\n    [SR_SubTypeItem_Name],\r\n    [SR_Urgency_Name],\r\n    [Hours_Actual],\r\n    CAST(\r\n        DATEDIFF(hh, [Date_Entered_UTC], GETUTCDATE()) / 24.0 AS DECIMAL(10, 1)\r\n    ) AS 'Age',\r\n    [Date_Resolved_UTC],\r\n    [Date_Resplan_UTC],\r\n    [Date_Responded_UTC],\r\n    [Resolved_Minutes],\r\n    [Resplan_Minutes],\r\n    [Responded_Minutes],\r\n    [IsInSla],\r\n    [Last_Update_UTC],\r\n    [ResourceList],\r\n    [Company_Name],\r\n    [Closed_By],\r\n    [SLA_Name],\r\n    [parentTicketId]\r\nFROM\r\n    [${cw_db_name}].[dbo].[v_api_collection_service_ticket]\r\nWHERE\r\n    [Closed_Flag] = 0 AND\r\n    [parentTicketId] IS NULL AND\r\n    [Board_Name] IN(${cw_board:sqlstring})\r\nORDER BY SR_Urgency_Name, Age DESC"
    }
   ]
  },
  {
   "title": "Open Support Tickets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\r\nFROM\r\n    [${cw_db_name}].[dbo].[v_api_collection_service_ticket]\r\nWHERE\r\n    [Board_Name] IN(${cw_board:sqlstring}) AND\r\n    [Closed_Flag] = 0 AND\r\n    [parentTicketId] IS NULL"
    }
   ]
  },
  {
   "title": "Tickets Opened vs Closed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    $__timeGroup([Date_Entered_UTC], '1d', 0) AS 'time',\r\n    ISNULL(COUNT([SR_Service_RecID]), 0) AS 'Opened Tickets'\r\nFROM\r\n    [${cw_db_name}].[dbo].[v_api_collection_service_ticket]\r\nWHERE\r\n    [Board_Name] IN(${cw_board:sqlstring}) AND\r\n    [Entered_By] IN(${cw_user:sqlstring}) AND\r\n    [parentTicketId] IS NULL AND\r\n    $__timeFilter([Date_Entered_UTC])\r\nGROUP BY\r\n    $__timeGroup([Date_Entered_UTC], '1d', 0)\r\nORDER BY $__timeGroup([Date_Entered_UTC], '1d', 0)"
    },
    {
     "rawSql": "SELECT\r\n    $__timeGroup([Date_Closed_UTC], '1d', 0) AS 'time',\r\n    ISNULL(COUNT([SR_Service_RecID]), 0) AS 'Closed Tickets'\r\nFROM\r\n    [${cw_db_name}].[dbo].[v_api_collection_service_ticket]\r\nWHERE\r\n    [Board_Name] IN(${cw_board:sqlstring}) AND\r\n    [Closed_By] IN(${cw_user:sqlstring}) AND\r\n    [parentTicketId] IS NULL AND\r\n    $__timeFilter([Date_Closed_UTC])\r\nGROUP BY $__timeGroup([Date_Closed_UTC], '1d', 0)\r\nORDER BY $__timeGroup([Date_Closed_UTC], '1d', 0)"
    }
   ]
  },
  {
   "title": "Closed Tickets",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT [Closed_By], COUNT(*) AS 'Closed Count'\r\nFROM\r\n    [${cw_db_name}].[dbo].[v_api_collection_service_ticket]\r\nWHERE\r\n    [Board_Name] IN(${cw_board:sqlstring}) AND\r\n    [ResourceList] IN(${cw_user:sqlstring}) AND\r\n    [Closed_Flag] = 1 AND\r\n    [parentTicketId] IS NULL AND\r\n    $__timeFilter([Date_Closed_UTC]) AND\r\n    [Hours_Actual] > 0\r\nGROUP BY [Closed_By]\r\nORDER BY 'Closed Count' DESC"
    }
   ]
  },
  {
   "title": "Ticket Statuses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT [Status_Name], COUNT(*) AS 'Status'\r\nFROM\r\n    [${cw_db_name}].[dbo].[v_api_collection_service_ticket]\r\nWHERE\r\n    [Board_Name] IN(${cw_board:sqlstring}) AND\r\n    [ResourceList] IN(${cw_user:sqlstring}) AND\r\n    [parentTicketId] IS NULL AND\r\n    [Status_Name] NOT LIKE '>%' AND\r\n    $__timeFilter([Date_Closed_UTC])\r\nGROUP BY [Status_Name]\r\nORDER BY 'Status' DESC"
    }
   ]
  }
 ]
}